### ISSUE TITLE
The source code in this repo is different than the source for download at KM

### ISSUE THREAD

**Issue by cdmckay** [kissmetrics/km-wordpress#3]
This source code says version 0.0.1, but if you use the download link at kissmetrics.com (https://s3.amazonaws.com/kissmetrics-support-files/assets/integrations/wordpress/kissmetrics.zip) then it shows version 0.0.2.

Why is that?

**Comment by paulgoleary** [comment]
This has been addressed. 0.0.2 is merged. 0.0.3 is forthcoming as well. Thanks.
